### ISSUE TITLE
upload 0.0.2 to the forge

### ISSUE THREAD

**Issue by gpetras** [arioch/puppet-ulimit#7]
Hey @arioch, looks like there are quite a few improvements between 0.0.1 and 0.0.2. Can you release 0.0.2 to Puppet Forge?

Thanks!

Greg

**Comment by arioch** [comment]
Sure thing.
Here you go: https://forge.puppetlabs.com/arioch/ulimit/0.0.2/readme.

**Comment by gpetras** [comment]
Thanks @arioch!
